[package]
name = "pairipcore"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5.26", features = ["derive"] }
colored = "3.0.0"
hex = "0.4.3"
itertools = "0.14.0"
