name: Rust Build
on: [push]  # 触发工作流的 GitHub 事件，这里设置为在 push 事件时触发
jobs:
     build:
       runs-on: ubuntu-latest  # 使用最新版本的 Ubuntu 作为运行环境

       steps:
       - uses: actions/checkout@v2  # 检出仓库

       - name: Install Rust
         uses: actions-rs/toolchain@v1
         with:
           toolchain: stable  # 指定 Rust 工具链版本
           override: true

       - name: Build
         run: cargo build --verbose  # 运行 cargo build 命令

       - name: Upload artifacts
         uses: actions/upload-artifact@v2
         with:
           name: rust-binary  # 工件名称，可以是任何你喜欢的名字
           path: target/release/  # 指定要上传的文件或目录路径
